---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: docker
  commands:
  - docker stop question-app
  - docker pull osheychik/question-app
  - docker run -d --rm -p 23480:8080 --name question-app osheychik/question-app
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

...
