---
kind: pipeline
name: Build and deploy

platform:
  os: linux
  arch: amd64

steps:
- name: build docker image
  image: docker
  commands:
  - docker build .
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: deploy
  image: docker
  commands:
  - docker stop question-app || true
  - docker pull osheychik/question-app
  - docker run -d --rm -p 23480:8080 --name question-app osheychik/question-app
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    branch:
    - master

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

...
