---
kind: pipeline
name: Build and deploy

platform:
  os: linux
  arch: amd64

steps:
- name: build docker image
  image: docker
  commands:
  - docker build -t question-app:latest .
  - docker image prune --filter label=stage=intermediate -f
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: deploy
  image: docker
  commands:
  - docker stop question-app || true
  - docker run -d --rm -p 23480:8080 --name question-app question-app:latest
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    branch:
    - master

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

...
